services:
  app: 
    image: 'bloggerapp'
    ports:
      - 5123:5123
    build: ./
    container_name: bloggerapp
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=localhost
    ports:
      - "8082:5432"