services:
  app:
    image: 'bloggerapp'
    ports:
      - 5123:5123
    container_name: blogger_app
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=localhost
    ports:
      - 5432:5432